import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import {playwriteVN, roboto} from "../utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playwriteVN.variable} ${roboto.variable}`}
      >
        <Header />
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
